# recipe.yaml

{{ $imgname := or .imgname "6tops" }}
{{ $buildnr := or .buildnr "b0" }}
{{ $window := or .window "wayland" }}

architecture: arm64

actions:
- action: recipe
  recipe: ./ospack.yaml
  variables:
    hostname: {{ $imgname }}

- action: recipe
  recipe: ./osvideopack.yaml
  variables:
    window: {{ $window }}

- action: recipe
  recipe: ./image.yaml
  variables:
    buildnr: {{ $buildnr }}
