# recipe.yaml

{{ $imgname := or .imgname "6tops" }}
{{ $buildnr := or .buildnr "b0" }}

architecture: arm64

actions:
- action: recipe
  recipe: ./ospack.yaml
  variables:
    hostname: {{ $imgname }}

- action: recipe
  recipe: ./osvideopack.yaml

- action: recipe
  recipe: ./image.yaml
  variables:
    buildnr: {{ $buildnr }}
